ALTER SESSION SET "_ORACLE_SCRIPT"=true;

CREATE USER Banking_Project IDENTIFIED BY mindgate123;

GRANT CONNECT, DBA TO Banking_Project;

--===============================================================================
CREATE TABLE user_details (
    user_id NUMBER(10)GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50)NOT NULL,
    password VARCHAR2(50) NOT NULL,
    dob DATE NOT NULL,
    user_type VARCHAR(10) default 'user',
    email_Id VARCHAR2(100) NOT NULL,
    gender VARCHAR2(10) NOT NULL,
    address VARCHAR2(255)NOT NULL,
    phone_number NUMBER NOT NULL,
    reg_date DATE NOT NULL,
    login_count NUMBER DEFAULT 0,
    login_active VARCHAR2(20) DEFAULT 'false',
    
    CONSTRAINT ck_user_type CHECK(user_type in ('user', 'admin')),
    CONSTRAINT ck_login_count CHECK (login_count in (0, 1, 2, 3))
);

--CREATING INDEXES FOR THE TABLE S AS TO SEARCH WHILE LOGGIN IN
CREATE INDEX phone_number_i ON user_details(phone_number);
CREATE INDEX email_id_i ON user_details(email_id);
--===============================================================================

CREATE TABLE account_details (
    account_number NUMBER(16) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER(10) NOT NULL,
    account_type VARCHAR2(50) NOT NULL,
--    account_status VARCHAR2(20) DEFAULT 'false',
    actual_balance NUMBER DEFAULT 0 NOT NULL,
    overderaft_opted VARCHAR2(5) NOT NULL,
    overdraft_balance NUMBER ,
    overdraft_charges NUMBER ,
   
    CONSTRAINT ck_account_type CHECK(account_type IN ('saving', 'current')),
    CONSTRAINT fk_user_id FOREIGN KEY(user_id) REFERENCES user_details(user_Id)
);

--===============================================================================
CREATE TABLE fixed_deposit_details (
    fd_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER(10) NOT NULL,
    fd_creation_date DATE NOT NULL,
    fd_amount NUMBER(10 ,2) NOT NULL,
    fd_tenure NUMBER NOT NULL,
    fd_maturity_date DATE NOT NULL,
    rate_of_interest NUMBER NOT NULL,
    account_number NUMBER(16) NOT NULL,
    
    CONSTRAINT fk_fd_user_id FOREIGN KEY (user_id) REFERENCES user_details(user_id),
    CONSTRAINT fk_account_number FOREIGN KEY (account_number) REFERENCES account_details(account_number)
);

--===============================================================================

CREATE TABLE Cheque_details (
    issuer_account_no NUMBER(16) NOT NULL,
    cheque_no NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    benificiary_account_no NUMBER(16),
    deposit_date DATE,
    cheque_amount NUMBER(10,2),
    cheque_status VARCHAR2(20) DEFAULT('Not recieved'),
    
    CONSTRAINT fk_issuer_account_no FOREIGN KEY (issuer_account_no) REFERENCES account_details(account_number),
    CONSTRAINT fk_benificiary_account_no FOREIGN KEY (benificiary_account_no) REFERENCES account_details(account_number),
    CONSTRAINT ck_cheque_status CHECK(cheque_status IN ('Not recieved', 'sent for clearence', 'cleared', 'bounced'))
);

ALTER TABLE cheque_details MODIFY (cheque_no NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY); 
commit;
drop table cheque_details;
--===============================================================================

CREATE TABLE transaction_details (
    transaction_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issuer_account_no NUMBER(16) NOT NULL,
    benificiary_account_no NUMBER(16) NOT NULL,
    transaction_type VARCHAR2(50) NOT NULL,
    transaction_mode VARCHAR(50) NOT NULL,
    transaction_amount NUMBER(10, 2) NOT NULL,
    remarks VARCHAR2(255),
    transaction_status VARCHAR2(50) NOT NULL,
    transaction_date DATE NOT NULL,
    
    CONSTRAINT fk_trans_issuer_account_no FOREIGN KEY (issuer_account_no) REFERENCES account_details(account_number),
    CONSTRAINT fk_trans_benificiary_account_no FOREIGN KEY (benificiary_account_no) REFERENCES Account_details(account_number),
    CONSTRAINT ck_transaction_type CHECK(transaction_type IN ('debit', 'credit')),
    CONSTRAINT ck_transaction_mode CHECK(transaction_mode IN ('cheque', 'account-transfer')),
    CONSTRAINT ck_transaction_status CHECK(transaction_status IN ('success', 'failed')) 
);
--===============================================================================

drop table account_details;
DROP TABLE user_Details;
drop table fixed_deposit_details;
drop Table cheque_details;
drop table transaction_details;

--===============================================================================

-- Inserting into user_details table
INSERT INTO user_details (first_name, last_name, password, dob, user_type, Email_Id, Gender, address, phone_number, Reg_Date)
VALUES ('John', 'Doe', 'password123', TO_DATE('1990-05-15', 'YYYY-MM-DD'), 'user', 'john.doe@example.com', 'Male', '123 Main St, City, Country', 1234567890, SYSDATE);

-- Inserting into account_details table
INSERT INTO account_details (user_id, account_type, actual_balance, overderaft_opted)
VALUES (1, 'saving', 1000, 'no');

-- Inserting into fixed_deposit_details table
INSERT INTO fixed_deposit_details (user_id, fd_creation_date, fd_amount, fd_tenure, fd_maturity_date, rate_of_interest, account_number)
VALUES (1, SYSDATE, 5000, 12, ADD_MONTHS(SYSDATE, 12), 5.5, 1);

-- Inserting into Cheque_details table
INSERT INTO Cheque_details (issuer_account_no, cheque_no, benificiary_account_no, deposit_date, cheque_amount, cheque_status)
VALUES (1, '123456', 2, SYSDATE, 1000, 'Not recieved');

-- Inserting into transaction_details table
INSERT INTO transaction_details (issuer_account_no, benificiary_account_no, transaction_type, transaction_mode, transaction_amount, remarks, transaction_status, transaction_date)
VALUES (1, 1, 'debit', 'cheque', 500, 'Payment for services', 'success', SYSDATE);

--===============================================================================

select * from USER_DETAILS;
select * from ACCOUNT_DETAILS;
select * from FIXED_DEPOSIT_DETAILS;
select * from CHEQUE_DETAILS;
select * from TRANSACTION_DETAILS;
commit;
SELECT u.* FROM Cheque_details u WHERE trunc(deposit_date) = '21-05-2024' AND benificiary_account_no = '5';
SELECT * FROM user_details WHERE login_active = 'false';
-- Inserting into user_details table (Part 1)
INSERT INTO user_details (first_name, last_name, password, dob, user_type, Email_Id, Gender, address, phone_number, Reg_Date, login_count, login_active)
VALUES 
('John', 'Doe', 'password1', TO_DATE('1990-05-15', 'YYYY-MM-DD'), 'user', 'john.doe@example.com', 'Male', '123 Main St, City, Country', 1234567890, SYSDATE, 2, 'true');

-- Inserting into user_details table (Part 2)
INSERT INTO user_details (first_name, last_name, password, dob, user_type, Email_Id, Gender, address, phone_number, Reg_Date, login_count, login_active)
VALUES 
('Alice', 'Smith', 'password2', TO_DATE('1985-10-20', 'YYYY-MM-DD'), 'admin', 'alice.smith@example.com', 'Female', '456 Elm St, Town, Country', 9876543210, SYSDATE, 1, 'false');

-- Inserting into user_details table (Part 3)
INSERT INTO user_details (first_name, last_name, password, dob, user_type, Email_Id, Gender, address, phone_number, Reg_Date, login_count, login_active)
VALUES 
('Mike', 'Johnson', 'password3', TO_DATE('1992-08-25', 'YYYY-MM-DD'), 'user', 'mike.johnson@example.com', 'Male', '789 Oak St, Village, Country', 6543210987, SYSDATE, 0, 'true');

-- Inserting into user_details table (Part 4)
INSERT INTO user_details (first_name, last_name, password, dob, user_type, Email_Id, Gender, address, phone_number, Reg_Date, login_count, login_active)
VALUES 
('Emily', 'Brown', 'password4', TO_DATE('1988-04-12', 'YYYY-MM-DD'), 'user', 'emily.brown@example.com', 'Female', '101 Pine St, Hamlet, Country', 3210987654, SYSDATE, 3, 'true');

-- Inserting into user_details table (Part 5)
INSERT INTO user_details (first_name, last_name, password, dob, user_type, Email_Id, Gender, address, phone_number, Reg_Date, login_count, login_active)
VALUES 
('Chris', 'Wilson', 'password5', TO_DATE('1995-12-30', 'YYYY-MM-DD'), 'admin', 'chris.wilson@example.com', 'Male', '202 Cedar St, City, Country', 5678901234, SYSDATE, 1, 'false');

--==========================================================
-- Part 1
INSERT INTO account_details (user_id, account_type, actual_balance, overderaft_opted, overdraft_balance, overdraft_charges)
VALUES 
(1, 'saving', 5000, 'no', NULL, NULL);

-- Part 2
INSERT INTO account_details (user_id, account_type, actual_balance, overderaft_opted, overdraft_balance, overdraft_charges)
VALUES 
(2, 'current', 10000, 'yes', 2000, 50);

-- Part 3
INSERT INTO account_details (user_id, account_type, actual_balance, overderaft_opted, overdraft_balance, overdraft_charges)
VALUES 
(3, 'saving', 3000, 'no', NULL, NULL);

-- Part 4
INSERT INTO account_details (user_id, account_type, actual_balance, overderaft_opted, overdraft_balance, overdraft_charges)
VALUES 
(1, 'saving', 7000, 'no', 0, 00);

-- Part 5
INSERT INTO account_details (user_id, account_type, actual_balance, overderaft_opted, overdraft_balance, overdraft_charges)
VALUES 
(5, 'saving', 2000, 'no', NULL, NULL);

--==============================================================================
-- Part 1
INSERT INTO fixed_deposit_details (user_id, fd_creation_date, fd_amount, fd_tenure, fd_maturity_date, rate_of_interest, account_number)
VALUES 
(1, SYSDATE, 10000, 12, ADD_MONTHS(SYSDATE, 12), 5.5, 1);

-- Part 2
INSERT INTO fixed_deposit_details (user_id, fd_creation_date, fd_amount, fd_tenure, fd_maturity_date, rate_of_interest, account_number)
VALUES 
(2, SYSDATE, 15000, 24, ADD_MONTHS(SYSDATE, 24), 6.0, 2);

-- Part 3
INSERT INTO fixed_deposit_details (user_id, fd_creation_date, fd_amount, fd_tenure, fd_maturity_date, rate_of_interest, account_number)
VALUES 
(3, SYSDATE, 8000, 18, ADD_MONTHS(SYSDATE, 18), 5.75, 3);

-- Part 4
INSERT INTO fixed_deposit_details (user_id, fd_creation_date, fd_amount, fd_tenure, fd_maturity_date, rate_of_interest, account_number)
VALUES 
(4, SYSDATE, 12000, 12, ADD_MONTHS(SYSDATE, 12), 5.25, 4);

-- Part 5
INSERT INTO fixed_deposit_details (user_id, fd_creation_date, fd_amount, fd_tenure, fd_maturity_date, rate_of_interest, account_number)
VALUES 
(5, SYSDATE, 5000, 24, ADD_MONTHS(SYSDATE, 24), 6.25, 5);

--========================================================================================
-- Part 1
INSERT INTO Cheque_details (issuer_account_no, cheque_no, benificiary_account_no, deposit_date, cheque_amount, cheque_status)
VALUES 
(1, '123456', 2, SYSDATE, 1000, 'Not recieved');

-- Part 2
INSERT INTO Cheque_details (issuer_account_no, cheque_no, benificiary_account_no, deposit_date, cheque_amount, cheque_status)
VALUES 
(2, '654321', 3, SYSDATE, 2000, 'sent for clearence');

-- Part 3
INSERT INTO Cheque_details (issuer_account_no, cheque_no, benificiary_account_no, deposit_date, cheque_amount, cheque_status)
VALUES 
(3, '987654', 4, SYSDATE, 3000, 'cleared');

-- Part 4
INSERT INTO Cheque_details (issuer_account_no, cheque_no, benificiary_account_no, deposit_date, cheque_amount, cheque_status)
VALUES 
(4, '456789', 5, SYSDATE, 4000, 'Not recieved');

-- Part 5
INSERT INTO Cheque_details (issuer_account_no, cheque_no, benificiary_account_no, deposit_date, cheque_amount, cheque_status)
VALUES 
(5, '789123', 1, SYSDATE, 5000, 'sent for clearence');

--=======================================================================================
-- Part 1
INSERT INTO transaction_details (issuer_account_no, benificiary_account_no, transaction_type, transaction_mode, transaction_amount, remarks, transaction_status, transaction_date)
VALUES 
(1, 2, 'debit', 'cheque', 500, 'Payment for services', 'success', SYSDATE);

-- Part 2
INSERT INTO transaction_details (issuer_account_no, benificiary_account_no, transaction_type, transaction_mode, transaction_amount, remarks, transaction_status, transaction_date)
VALUES 
(2, 3, 'credit', 'account-transfer', 1000, 'Refund', 'success', SYSDATE);

-- Part 3
INSERT INTO transaction_details (issuer_account_no, benificiary_account_no, transaction_type, transaction_mode, transaction_amount, remarks, transaction_status, transaction_date)
VALUES 
(3, 4, 'debit', 'cheque', 1500, 'Payment for goods', 'success', SYSDATE);

-- Part 4
INSERT INTO transaction_details (issuer_account_no, benificiary_account_no, transaction_type, transaction_mode, transaction_amount, remarks, transaction_status, transaction_date)
VALUES 
(4, 5, 'credit', 'account-transfer', 2000, 'Salary', 'success', SYSDATE);

-- Part 5
INSERT INTO transaction_details (issuer_account_no, benificiary_account_no, transaction_type, transaction_mode, transaction_amount, remarks, transaction_status, transaction_date)
VALUES 
(5, 1, 'debit', 'cheque', 2500, 'Payment for rent', 'success', SYSDATE);

--======================================================================================================
desc user_details; 
desc account_details;
desc CHEQUE _DETAILS;
Delete from user_details where user_id = 21;
commit;
update USER_DETAILS Set login_count = 1 where user_id = 2;
select u.*,acc.* from user_details u inner join account_details acc on u.user_id = acc.user_id where acc.user_id=2;
SELECT * FROM user_details WHERE user_id = 1;
c
SELECT * FROM transaction_details WHERE issuer_account_no = 1;


SELECT a.*, b.*, c.* 
FROM cheque_details a JOIN ACCOUNT_DETAILS b 
ON a.issuer_account_no = b.ACCOUNT_NUMBER 
JOIN ACCOUNT_DETAILS c 
ON a.issuer_account_no = c.ACCOUNT_NUMBER  
WHERE cheque_status IN ('Not recieved', 'sent for clearence');



commit;





SELECT 
    a.*, 
    
    b.ACCOUNT_NUMBER AS issuer_account_number, 
    b.USER_ID AS issuer_user_id,
    b.ACCOUNT_TYPE AS issuer_account_type,
    b.ACCOUNT_STATUS AS issuer_account_status,
    b.ACTUAL_BALANCE AS issuer_actual_balance,
    b.OVERDERAFT_OPTED AS issuer_overdraft_opted,
    b.OVERDRAFT_BALANCE AS issuer_overdraft_balance,
    b.OVERDRAFT_CHARGES AS issuer_overdraft_charges,
    
    c.ACCOUNT_NUMBER AS bf_account_number, 
    c.USER_ID AS bf_user_id,
    c.ACCOUNT_TYPE AS bf_account_type,
    c.ACCOUNT_STATUS AS bf_account_status,
    c.ACTUAL_BALANCE AS bf_actual_balance,
    c.OVERDERAFT_OPTED AS bf_overdraft_opted,
    c.OVERDRAFT_BALANCE AS bf_overdraft_balance,
    c.OVERDRAFT_CHARGES AS bf_overdraft_charges,    
    
FROM cheque_details a JOIN ACCOUNT_DETAILS b ON a.issuer_account_no = b.ACCOUNT_NUMBER 
JOIN ACCOUNT_DETAILS c ON a.BENIFICIARY_ACCOUNT_NO = c.ACCOUNT_NUMBER
WHERE cheque_status IN ('Not received', 'sent for clearance');


SELECT 
    a.*, 
    
    b.ACCOUNT_NUMBER AS issuer_account_number,
    b.USER_ID AS issuer_user_id,
    b.ACCOUNT_TYPE AS issuer_account_type,
  
    b.ACTUAL_BALANCE AS issuer_actual_balance,
    b.OVERDERAFT_OPTED AS issuer_overdraft_opted,
    b.OVERDRAFT_BALANCE AS issuer_overdraft_balance,
    b.OVERDRAFT_CHARGES AS issuer_overdraft_charges,
    
    c.ACCOUNT_NUMBER AS bf_account_number,
    c.USER_ID AS bf_user_id,
    c.ACCOUNT_TYPE AS bf_account_type,
  
    c.ACTUAL_BALANCE AS bf_actual_balance,
    c.OVERDERAFT_OPTED AS bf_overdraft_opted,
    c.OVERDRAFT_BALANCE AS bf_overdraft_balance,
    c.OVERDRAFT_CHARGES AS bf_overdraft_charges,
    
    u1.email_id AS issuer_email, u2.email_id AS beneficiary_email
FROM 
    ACCOUNT_DETAILS b 
JOIN 
   cheque_details a  ON a.issuer_account_no = b.ACCOUNT_NUMBER 
JOIN 
    ACCOUNT_DETAILS c ON a.benificiary_account_no = c.ACCOUNT_NUMBER  -- Changed the join condition to the appropriate column
JOIN 
    USER_DETAILS u1 ON b.user_id = u1.user_id
JOIN 
    USER_DETAILS u2 ON c.user_id = u2.user_id
WHERE 
    a.cheque_status IN('Not recieved', 'sent for clearance');

commit;
 
SELECT * FROM user_details
; WHERE user_id = 2;

SELECT u.* FROM Cheque_details u WHERE trunc(deposit_date) = trunc(SYSDATE) AND benificiary_account_no = 3 AND cheque_status = 'Not recieved';
UPDATE user_details SET login_count = 0, login_active = 'true' WHERE user_id =1; AND login;

ALTER TABLE account_details DROP COLUMN account_status;
SET AUTOCOMMIT ON;

select * from cheque_details;

UPDATE account_details SET actual_balance = 10999, overdraft_balance = 191919, overdraft_charges=101 WHERE account_number = 1;

select * from account_details;  
commit;

SET AUTOCOMMIT ON;
SELECT * FROM transaction_details; WHERE issuer_account_no = 3;
select * from user_details;

UPDATE account_details SET actual_balance = 9000, overdraft_balance = 0, overdraft_charges=0 WHERE account_number = 3;



INSERT INTO account_details (user_id, account_type, actual_balance, overderaft_opted, overdraft_balance, overdraft_charges)
VALUES 
(5, 'saving', 10000, 'no', 0, 0);



INSERT INTO account_details (user_id, account_type, actual_balance, overderaft_opted, overdraft_balance, overdraft_charges)
VALUES 
(2, 'current', 10000,  'yes', 30000, 200);

commit;


INSERT INTO Cheque_details (issuer_account_no)values(61);




SELECT a.*, b.ACCOUNT_NUMBER AS issuer_account_number, b.USER_ID AS issuer_user_id, b.ACCOUNT_TYPE AS issuer_account_type, b.ACTUAL_BALANCE AS issuer_actual_balance, b.OVERDERAFT_OPTED AS issuer_overdraft_opted, b.OVERDRAFT_BALANCE AS issuer_overdraft_balance, b.OVERDRAFT_CHARGES AS issuer_overdraft_charges, c.ACCOUNT_NUMBER AS bf_account_number, c.USER_ID AS bf_user_id, c.ACCOUNT_TYPE AS bf_account_type, c.ACTUAL_BALANCE AS bf_actual_balance, c.OVERDERAFT_OPTED AS bf_overdraft_opted, c.OVERDRAFT_BALANCE AS bf_overdraft_balance, c.OVERDRAFT_CHARGES AS bf_overdraft_charges FROM ACCOUNT_DETAILS b JOIN cheque_details a ON a.issuer_account_no = b.ACCOUNT_NUMBER JOIN ACCOUNT_DETAILS c ON a.benificiary_account_no = c.ACCOUNT_NUMBER WHERE a.cheque_status IN('Not recieved', 'sent for clearence');


SELECT u.*, acc_issuer.* FROM Cheque_details u INNER JOIN account_details acc_issuer ON u.issuer_account_no = acc_issuer.account_number
                                                                WHERE u.issuer_account_no = 1;



SELECT * FROM transaction_details; WHERE issuer_account_no =2 OR  benificiary_account_no=2; 



SELECT * FROM transaction_details;
select * FROM account_details;
SELECt   * FROM user_details;

select * from Cheque_details;
commit;


SELECT * FROM Cheque_details WHERE deposit_date = TRUNC(SYSDATE);
SELECT TO_CHAR(deposit_date, 'YYYY-MM-DD HH24:MI:SS')
FROM Cheque_details
WHERE ROWNUM <= 10; -- Retrieves the formatted date for the first 10 rows



UPDATE cheque-details SET benificiary_account_no=?,deposit_date=?,cheque_amount=?,cheque_status=? WHERE cheque_no=?;

SELECT u.* FROM Cheque_details u; WHERE trunc(deposit_date) =  trunc(sysdate) AND benificiary_account_no = '2';

SELECT SYSDATE FROM DUAL;
select * from account_details;
SELECT * FROM TRANSACTION_DETAILS where issuer_account_no = 84;

UPDATE account_details SET actual_balance = 10000, overdraft_balance = 50000, overdraft_charges = 0 WHERE account_number = 83;

select * from user_details;

update user_details SET login_count = 0 WHERE user_id = 4;

SELECT * FROM cheque_details WHERE cheque_status = 'Not recieved' AND issuer_account_no = 81;
SELECT * FROM cheque_details WHERE cheque_status = 'Not recieved' AND issuer_account_no = 2;
